server:
  port: 8189
  servlet:
    context-path: /security

spring:
  jpa:
    show-sql: true
    properties:
      hibernare:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc
